# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160726_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.TextField(default='', max_length=1024)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Baloon',
            new_name='Balloon',
        ),
    ]
